### PR TITLE
Update a bit and run re-fmt 💅🏼

### PR DESCRIPTION
**Pull request by kutyel**
Hey Einar! 👋 

I'm glad you could port your awesome fish to Reason 🎉 

I took the liberty to run re-fmt and add parcel as `devDependencies`, if you don't mind!

Also, I'm getting a weird error of `Maximum call stack exceeded`, I really wanted to see the fish! 😂 

stack

Can we fix it for future generations? 😁 

Thanks in advance!

### CODE REVIEW

**Comment by kutyel** [comment]
Forgot to mention that when we merge this, the github colors will update to reflect it's Reason code and not OCaml, win-win! 🙌

**Comment by einarwh** [comment]
Hi! I don't see how a massively recursive function could lead to call stack exhaustion! :-D

It seems to work in Firefox but not in Chrome.

**Comment by einarwh** [comment]
The current implementation is *very* naive in order to be easy to read. There's a lot that could be done for optimization and reducing the number of calls. Unfortunately I always stumble on weird syntax errors where I don't understand what Reason is complaining about.

**Comment by einarwh** [comment]
Case in point:
https://gist.github.com/einarwh/e5a744daafed65063f6c74645edc335c

Of course the moral of such stories is always that I'm blind and or don't understand Reason.

**Review by einarwh — APPROVED** [review]

**Comment by einarwh** [comment]
Thanks for the PR! It would be nice to fix the call stack exhaustion issue as well.

**Comment by kutyel** [comment]
Awesome, don't worry, I feel your pain! 😂 Thanks for merging! ❤️

**Pull request merged**
